# Generated by Django 5.2.5 on 2026-04-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='USD value at time of investment', max_digits=20),
        ),
        migrations.AlterField(
            model_name='userinvestment',
            name='amount',
            field=models.DecimalField(decimal_places=8, help_text='Amount in the actual coin', max_digits=20),
        ),
    ]
