# Generated by Django 6.0.4 on 2026-05-02 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_userinvestment_amount_usd_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITradingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_apy_range', models.CharField(help_text='e.g. 150% - 300%', max_length=50)),
                ('max_portfolio_size', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('minimum_amount', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='TradeExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_pair', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinvestment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='userinvestment',
            name='user',
        ),
        migrations.CreateModel(
            name='BotDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, help_text='Amount in crypto', max_digits=20)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('coin', models.CharField(max_length=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='investments.aitradingtier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_deployments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('roi_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_performance', to='investments.aitradingtier')),
            ],
        ),
        migrations.DeleteModel(
            name='InvestmentPlan',
        ),
        migrations.DeleteModel(
            name='UserInvestment',
        ),
    ]
